import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from '../components/hero'
import Featured from '../components/Featured'
import NewArrivals from '../components/NewArrivals'
import Brands from '../components/Brands'
import Collections from './Collections'
import ArticleSection from '../components/ArticleSection'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Hero />
        <Featured />
        <NewArrivals />
        <Collections />
        <Brands />
        <ArticleSection />
      </main>

    </div>
  )
}
