
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Featured from '../components/Featured'
import NewArrivals from '../components/NewArrivals'
import Brands from '../components/Brands'
import Collections from '../components/Collections'
import ArticleSection from '../components/ArticleSection'
import Review from '../components/Review'

import { sanityClient } from './../utils/client'
import KitchenCanvas from '../components/Canvas/Kitchen'

export default function Home({posts}) {
  const postsThree = posts.filter((item, index) => index < 4)
  return (
    <div className={styles.container}>
      <Head>
        <title>Furniture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Hero />
        <Featured postsThree={postsThree} />
        <Brands />
        <NewArrivals postsThree={postsThree}  />
        <Collections  />
        {/* <div className=' h-60 bg-[#ddd]'>
          <KitchenCanvas />
        </div> */}
        <Review />
        <ArticleSection />
      </main>

    </div>
  )
}


export async function getStaticProps() {
  const query = `*[_type == "post"]{
    _id,
    title,
    slug,
    mainImage,
    stock,
    price,
    categories
  }`;
  
  const posts = await sanityClient.fetch(query);


  return {
    props: {
      posts,
    }
  }
}
